export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    GET_REQUEST: 'GET_REQUEST',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_FAILURE: 'GET_FAILURE'
}

export const reqConst = {
    REQR_REQUEST: 'REQR_REQUEST',
    REQR_SUCCESS: 'REQR_SUCCESS',
    REQR_FAILURE: 'REQR_FAILURE',
    REQA_REQUEST: 'REQA_REQUEST',
    REQA_SUCCESS: 'REQA_SUCCESS',
    REQA_FAILURE: 'REQA_FAILURE',
    REQP_REQUEST: 'REQP_REQUEST',
    REQP_SUCCESS: 'REQP_SUCCESS',
    REQP_FAILURE: 'REQP_FAILURE',
    REQS_REQUEST: 'REQS_REQUEST',
    REQS_SUCCESS: 'REQS_SUCCESS',
    REQS_FAILURE: 'REQS_FAILURE',
}

export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",

    GET_CART_REQUEST: "GET_CART_REQUEST",
    GET_CART_SUCCESS: "GET_CART_SUCCESS",
    GET_CART_FAILURE: "GET_CART_FAILURE"
};

export const orderConst = {
    ORDER_REQUEST: "ORDER_REQUEST",
    ORDER_SUCCESS: "ORDER_SUCCESS",
    ORDER_FAILURE: "ORDER_FAILURE",
    GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    GET_ORDER_FAILURE: "GET_ORDER_FAILURE"
}

export const paymentConst = {
    BKASH_REQUEST: 'BKASH_REQUEST',
    BKASH_SUCCESS: 'BKASH_SUCCESS',
    BKASH_FAILURE: 'BKASH_FAILURE'
}